### ISSUE TITLE
IndexError on reload 

### ISSUE THREAD

**Issue by ervinpopescu** [elParaguayo/qtile-extras#126]
**It does not crash qtile**

```
2022-10-04 14:58:55,224 ERROR libqtile loop.py:_handle_exception():L63 list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 862, in f
    func(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 580, in draw
    self.drawer.clear(self.background or self.bar.background)
  File "/home/ervin/.config/qtile-x11/qtile_extras/widget/decorations.py", line 706, in new_clear
    self._clear(colour)
  File "/home/ervin/.config/qtile-x11/qtile_extras/widget/decorations.py", line 282, in draw
    if self.is_first:
  File "/home/ervin/.config/qtile-x11/qtile_extras/widget/decorations.py", line 255, in is_first
    grouped = self._get_parent_group()
  File "/home/ervin/.config/qtile-x11/qtile_extras/widget/decorations.py", line 218, in _get_parent_group
    current = [grouped[0]]
IndexError: list index out of range
```
Having investigated just a bit, the widgets seem to be initialized correctly( i.e. `widgets` in `_get_parent_group` is not None on reload). This is weird.

**Comment by elParaguayo** [comment]
Odd. Can you share your config?

**Comment by ervinpopescu** [comment]
https://github.com/ervinpopescu/dots-Lenovo/.config/qtile

It's up to date.

**Comment by elParaguayo** [comment]
If you take the grouped widgets out of the `WidgetBox`, does that remove the error message?

**Comment by ervinpopescu** [comment]
It does.

**Comment by elParaguayo** [comment]
No, that's fine. I'm just trying to track down the cause of the issue.

**Comment by elParaguayo** [comment]
Are you able to test the fix in #128?

**Comment by ervinpopescu** [comment]
Will do that ASAP.

**Comment by ervinpopescu** [comment]
Yes, that fixes it.
