### ISSUE TITLE
Visualizer utilization issue 

### ISSUE THREAD

**Issue by DeeeeLAN** [elParaguayo/qtile-extras#135]
When I leave the visualizer enabled in my config, after a few hours my computer is highly unresponsive and htop shows qtile pegging 100% utilization. It goes away when I reload, but always comes back after a few hours. I think this might be related to some of my other performance-related tickets I have filed here or on the main repo. Disabling visualizer makes the problem go away.

**Comment by DeeeeLAN** [comment]
Maybe qtile/qtile#3877 is related.

**Comment by elParaguayo** [comment]
There's definitely something wrong with this widget. Feels like a memory leak but not entirely obvious where it's coming from.

**Comment by elParaguayo** [comment]
The segfault is linked to this and should be fixed in #158.

Would be great if you could test.

**Comment by DeeeeLAN** [comment]
```bash
2022-11-08 14:03:21,510 ERROR libqtile base.py:_wrapper():L355 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 353, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.10/site-packages/qtile_extras/widget/visualiser.py", line 172, in _open_shm
    self._lockfile = open(LOCK, "rb+")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lock.mmap'
```

**Comment by elParaguayo** [comment]
Sigh...

That file should have been created by the separate `cava_draw.py` process. Can you check if that's running?

**Comment by DeeeeLAN** [comment]
Sorry, missed a line in the error message. Might be relevant.

**Comment by elParaguayo** [comment]
Can you try running `python /usr/lib/python3.10/site-packages/qtile_extras/resources/visualiser/cava_draw.py` from a terminal.

**Comment by DeeeeLAN** [comment]
```bash
> python cava_draw.py --width 100 --height 32 --bars 12 --spacing 2 --pipe /tmp/cava.pipe --background "#ffffff"
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qtile_extras/resources/visualiser/cava_draw.py", line 139, in <module>
    draw_cava(
  File "/usr/lib/python3.10/site-packages/qtile_extras/resources/visualiser/cava_draw.py", line 49, in draw_cava
    with mmap.mmap(
PermissionError: [Errno 13] Permission denied
```

**Comment by elParaguayo** [comment]
Well that's even stranger as it can open the file (as opposed to file not found error message).

What I don't understand is why it worked when I tested it and now I'm getting the same error today.

**Comment by elParaguayo** [comment]
Pushed a change. Working again for me now.

**Comment by DeeeeLAN** [comment]
Something is still off for me. After rebooting, I got this:
```bash
2022-11-08 15:50:59,572 ERROR libqtile manager.py:spawn():L1197 couldn't find `/usr/lib/python3.10/site-packages/qtile_extras/resources/visualiser/cava_draw.py`
2022-11-08 15:51:00,573 ERROR libqtile base.py:_wrapper():L355 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 353, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.10/site-packages/qtile_extras/widget/visualiser.py", line 172, in _open_shm
    self._lockfile = open(LOCK, "rb+")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lock.mmap'
```
I tried launching it manually to see and permissions are working there - no errors at least. I restarted qtile with `qtile cmd-obj -o cmd -f restart` then tried again and got this in the log:
```bash
2022-11-08 15:51:40,205 ERROR libqtile manager.py:spawn():L1197 couldn't find `/usr/lib/python3.10/site-packages/qtile_extras/resources/visualiser/cava_draw.py`
2022-11-08 15:51:41,206 ERROR libqtile base.py:_wrapper():L355 got exception from widget timer
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 353, in _wrapper
    method(*method_args)
  File "/usr/lib/python3.10/site-packages/qtile_extras/widget/visualiser.py", line 176, in _open_shm
    self._shm = mmap.mmap(
ValueError: mmap length is greater than file size
```

**Comment by elParaguayo** [comment]
`cava_draw.py` should be executable. Can you try making it executable and see if that makes a difference?

If it does, I'll update the widget so it just calls the script via `python <script>` instead.

**Comment by DeeeeLAN** [comment]
I pulled your update and the visualizer is visible again! I will let it run for a while to confirm I don't see any memory leak issues.

However, the bars it shows don't seem to match the bars if I run Cava directly. The beat seems to match, but the shape looks off some of the time.

**Comment by elParaguayo** [comment]
It doesn't do the symmetry that cava does by default. Is that the difference you're seeing?

**Comment by DeeeeLAN** [comment]
Yeah that is probably it. The left side seems more accurate than the right side. Cava directly supports a configurable number of bars - is it possible to pass that number through in a config and mirror cava more directly?

**Comment by elParaguayo** [comment]
Setting the number of bars in the widget changes the cava config for the widget.

I can add the option for the mirroring if that's desirable.

**Comment by DeeeeLAN** [comment]
Yeah that would be nice, I was expecting it to be a full ,tiny visualizer I guess.

**Comment by elParaguayo** [comment]
Ok - I've added the ability to have mirrored look. Pull the latest update and set `channels='stereo'` in the config.

Not sure what else you're after so let me know if there's anything else missing.

By default, the widget is meant to be small but you can make it as big as you want with as many bars as you want.

**Comment by elParaguayo** [comment]
CPU is going to be higher with it running as the widget is polling the data every 1/framerate seconds and you've got a script running to create the bar image at the same frequency *and* you've got cava running.

However, it sounds like it's good enough to merge for now!
