### ISSUE TITLE
Problem with UPowerWidget

### ISSUE THREAD

**Issue by matthewsia98** [elParaguayo/qtile-extras#167]
Nothing shows up when using this widget.

```
pip list | grep dbus                                              [18:58:06]
dbus-next            0.2.3
```

```
2022-11-09 18:56:43,016 ERROR libqtile manager.py:_finalize_configurables():L301 exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 289, in _finalize_configurables
    widget.finalize()
  File "/usr/lib/python3.10/site-packages/qtile_extras-0.22.2.dev30+g9c4b1ef-py3.10.egg/qtile_extras/widget/upower.py", line 395, in finalize
    self.props.off_properties_changed(self.upower_change)
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: UPowerWidget has no attribute: props
```

**Comment by elParaguayo** [comment]
If you're using the latest git version of qtile-extras then you need the to be using the latest git version of qtile.

Your issue is that you're using the tagged release of qtile so you need to use the matching tagged release of qtile-extras.

**Comment by elParaguayo** [comment]
The first error is interesting as that shouldn't really happen. Was there a separate message when you started qtile? Something must have failed for `self.props` not to be set.

**Comment by matthewsia98** [comment]
Thanks, fixed.

I only installed installed the python dbus-next package.

Upon going through the logs I came across this line
```
2022-11-10 10:38:41,685 ERROR libqtile loop.py:_handle_exception():L63 The name org.freedesktop.UPower was not provided by any .service files
```

Doing a ```sudo pacman -S upower``` fixed it.
