### ISSUE TITLE
[Bug] Rect.Decoration not applied on widgets outside of qtile/qtile-extras

### ISSUE THREAD

**Issue by Crystal4276** [elParaguayo/qtile-extras#215]
Some quick context.
Each time there is a new version of qtile-git or qtile-extra-git, any local modification or PR which have not been merged is being erased. 
I was thinking i could workaround this by duplicating the relevant widget including the PR/modifications.
I'm trying to keep https://github.com/qtile/qtile/pull/4008, https://github.com/qtile/qtile/pull/3487 and https://github.com/qtile/qtile/issues/4009
When using any of those "custom" widgets, the Rect.Decoration is not applied.
![image](https://user-images.githubusercontent.com/27446196/205433223-17ec52e9-5133-4760-9d0c-59ad0c558983.png).
I ruled out the modification of the widget, because when the latter is made inside the original widget, Rect.Decoration are perfectly working.

An illustration with the groupbox widget above, i created a `widgets` folder as '~/.config/qtile/widgets' with modified groupbox inside (padgroupbox.py)
And modified config.py with:
``` python
from widgets.padgroupbox import padGroupBox

# General Decoration setting
decor_general = {
    "decorations": [
        RectDecoration(
            #colour="#a6e3a1",
            use_widget_background=True,
            line_width= 1,
            line_colour=colors[17],
            radius=[15, 15, 15, 15],
            filled=True,
            margin_y=20,
            padding_y=6,
            padding_x=0,
            group=True,
            clip=True,
        ),
    ],
}
box_main = {
            "font": 'Symbols Nerd Font Mono',
            "fontsize": 35,
            "spacing": 5,
            "margin_y": 2,
            "margin_x": 15,
            "padding_x": 5,
            "padding_y": 9,
            "background": colors[7],
            "disable_drag": True,
            "active": colors[3],
            "inactive": colors[2],
            "highlight_method":'line',
            "this_current_screen_border": colors[3],
            "other_current_screen_border": colors[4],
            "this_screen_border": colors[3],
            "highlight_color": colors[4],
            "borderwidth": 2,
            }
#Widget in Bar
                padGroupBox(
                    visible_groups=['1', '2', '3'], 
                    **box_main, 
                    **decor_nogroup
                    ),
```

**Comment by elParaguayo** [comment]
If I understand correctly, this may be relevant: https://qtile-extras.readthedocs.io/en/stable/manual/how_to/decorations.html#adding-decorations-to-user-defined-widgets

**Comment by Crystal4276** [comment]
Cool !

I assume that `from qtile.extras.widget import modify` should go to config.py.

So i tried with :

```python

from libqtile import bar, layout, hook, qtile
from qtile_extras import widget
from qtile_extras.widget.decorations import RectDecoration, PowerLineDecoration, BorderDecoration
from qtile.extras.widget import modify

Screen(
        top=bar.Bar(
            [
...
...
modify(padGroupBox,
                    visible_groups=['1', '2', '3'], 
                    **box_main, 
                    **decor_nogroup
                    ),
```
I get this error message.
Anything i missed ?

```python
2022-12-03 20:58:20,762 ERROR libqtile manager.py:reload_config():L281 Configuration error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 279, in reload_config
    self.config.load()
  File "/usr/lib/python3.10/site-packages/libqtile/confreader.py", line 125, in load
    self._reload_config_submodules(path)
  File "/usr/lib/python3.10/site-packages/libqtile/confreader.py", line 114, in _reload_config_submodules
    importlib.reload(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/crystal/.config/qtile/config.py", line 14, in <module>
    from qtile.extras.widget import modify
ModuleNotFoundError: No module named 'qtile'
```

**Comment by elParaguayo** [comment]
Check your last import line. It's not `qtile.extras.widget`. it's `qtile_extras.widget`.

**Comment by Crystal4276** [comment]
Yes all good ! 
It works
