### ISSUE TITLE
qtile-extras breaks built-in Notify widget.

### ISSUE THREAD

**Issue by ftpd** [elParaguayo/qtile-extras#233]
When I enable qtile_extras, my notifications from notify-send don't disappear from the statusbar. When I create one (using, for example, `notify-send`, I see this in log file:

````
2023-02-09 19:12:28,615 ERROR libqtile notify.py:close():L207 Exception in notifier close callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/notify.py", line 205, in close
    callback(nid)
  File "/usr/lib/python3.11/site-packages/libqtile/widget/notify.py", line 167, in on_close
    self._clear(ClosedReason.method)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/wayland/drawer.py", line 88, in clear
    self.set_source_rgb(colour, ctx=ctx)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/base.py", line 844, in set_source_rgb
    ctx.set_source_rgba(*utils.rgb(colour))
                         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/utils.py", line 106, in rgb
    raise ValueError("Invalid RGB specifier.")
ValueError: Invalid RGB specifier.
2023-02-09 19:12:36,159 ERROR pywayland.server listener.py:notify_func():L42 Exception in callback function
````

and when I click the notification (which normally closes it), I get:

````
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pywayland/server/listener.py", line 40, in notify_func
    callback(listener, data)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/wayland/core.py", line 447, in _on_cursor_button
    handled = self._process_cursor_button(button, pressed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/wayland/core.py", line 870, in _process_cursor_button
    self._hovered_window.process_button_click(
  File "/usr/lib/python3.11/site-packages/libqtile/bar.py", line 487, in process_button_click
    widget.button_press(
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 280, in button_press
    cmd()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/notify.py", line 196, in clear
    self._clear()
TypeError: Drawer.clear() missing 1 required positional argument: 'colour'
````

Everything works fine when I disable qtile-extras.

My setup:
- qtile 0.22.2.dev127+gffbf518e
- 0.22.2.dev98+g3ec2644

I'm enabling qtile_extras by adding the line `from qtile_extras import widget` in my config (I'm not importing 'widget' from libqtile).

**Comment by elParaguayo** [comment]
Thanks for posting this. I know what the issue is (the Notify has a method called `_clear` which is getting overwritten by the code injection that qtile_extras needs to do).

I'll probably end up fixing this in qtile rather than here but leave it with me.

**Comment by ftpd** [comment]
Thanks! Can you link to qtile's issue/PR when (if) you create it, so I can subscribe and track?

**Comment by elParaguayo** [comment]
Sure.
