### ISSUE TITLE
StatusNotifier mangles bar when nm-applet is running and 3 displays are connected

### ISSUE THREAD

**Issue by arjan-s** [elParaguayo/qtile-extras#239]
It's a bit hard to explain, so I'll let the screenshots do the talking.

Bar with nm-applet running and 2 displays connected:
![bar_with_2_displays](https://user-images.githubusercontent.com/10400299/223771741-45b7ec9d-8240-442f-8f60-7853681a29b3.png)

Same bar with nm-applet running and 3 displays connected:
![bar_with_3_displays](https://user-images.githubusercontent.com/10400299/223771746-4090221e-7fd0-42c4-9ca2-613f0da2bb1b.png)
and sometimes like this:
![bar_with_3_displays_option2](https://user-images.githubusercontent.com/10400299/223772707-32af0a4b-2361-4d8c-8447-6a24d9da8405.png)

When I stop/kill nm-applet the bar goes back to normal and displays correctly even when 3 monitors are connected.

Hopefully this makes sense to you. :)

**Comment by elParaguayo** [comment]
No. Makes no sense!

Anything in the log? Can you share config?

Not sure how I'm going to test this as I don't have 3 screens...

**Comment by elParaguayo** [comment]
For me, nm-applet isn't even showing in the `StatusNotifier` widget.

**Comment by arjan-s** [comment]
Sorry, I have to pick this up again...
Did you start nm-applet with the `--indicator` argument? Otherwise it'll use the old non-statusnotifier method.

**Comment by elParaguayo** [comment]
Ah. I see my problem. I don't have the required icons installed so the widget can't display anything. Let me fix that then I'll see if I can recreate your issue.

**Comment by elParaguayo** [comment]
Can't recreate this. However, I don't have multiple monitors so I can only use `fake_screens` in my config. No issue with 3 of those.

**Comment by arjan-s** [comment]
Just noticed I have errors in my log now that maybe explain this issue.

```
2023-08-30 11:07:49,476 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 261, in surface
    return self._surface
AttributeError: 'Img' object has no attribute '_surface'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 113, in __get__
    return _getattr(obj, self.under_name)
AttributeError: 'Img' object has no attribute '_width'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 200, in default_size
    return self._default_size
AttributeError: 'Img' object has no attribute '_default_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 191, in default_surface
    return self._default_surface
AttributeError: 'Img' object has no attribute '_default_surface'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/pkj7cgmz66assy7l18zc7j992npb41nx-python3-3.10.12/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/core/manager.py", line 933, in f
    func(*args)
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/bar.py", line 665, in _actual_draw
    i.draw()
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/widget/statusnotifier.py", line 700, in draw
    icon = item.get_icon(self.icon_size)
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/widget/statusnotifier.py", line 310, in get_icon
    base_icon = self.icon.surface
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 263, in surface
    surf, fmt = get_cairo_surface(self.bytes_img, self.width, self.height)
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 115, in __get__
    return self.get_default(obj)
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 139, in get_default
    size = obj.default_size
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 202, in default_size
    surf = self.default_surface
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 193, in default_surface
    surf, fmt = get_cairo_surface(self.bytes_img)
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 60, in get_cairo_surface
    return _decode_to_image_surface(bytes_img, width, height)
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/libqtile/images.py", line 40, in _decode_to_image_surface
    surf, fmt = cairocffi.pixbuf.decode_to_image_surface(bytes_img, width, height)
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/cairocffi/pixbuf.py", line 129, in decode_to_image_surface
    pixbuf, format_name = decode_to_pixbuf(image_data, width, height)
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/cairocffi/pixbuf.py", line 98, in decode_to_pixbuf
    handle_g_error(error, gdk_pixbuf.gdk_pixbuf_loader_write(
  File "/nix/store/mvc9mic052vpvi0rrpd5bj85zk4w9yam-python3-3.10.12-env/lib/python3.10/site-packages/cairocffi/pixbuf.py", line 64, in handle_g_error
    raise ImageLoadingError(message)
cairocffi.pixbuf.ImageLoadingError: Pixbuf error: Unrecognized image file format
```

**Comment by elParaguayo** [comment]
Do you know which app is causing that message?

I've seen that before when there's been no SVG support but that's just a guess.

**Comment by arjan-s** [comment]
Yeah it gets logged immediately when I start `nm-applet --indicator`, which is also what mangles up my bar. When I kill nm-applet again, the bar gets back to normal.

**Comment by elParaguayo** [comment]
OK - let me look into it.

**Comment by arjan-s** [comment]
Wow, no, I figured out the difference between my setups just now. The setup where this happens (with 3 monitors) has wired ethernet, while my other setup (with 2 monitors) only has wifi. If I disconnect my multiple monitors right now the bug remains, because it's caused by the connection type.

So in short: apparently nm-applet uses different types of icons:
- wired connected: works
- wireless: causes error
- connecting (animated whoosh thing around two circles): works
- not connected: causes error

**Comment by arjan-s** [comment]
And yes, it also happens in the stock widget, so I even posted the bug on the wrong tracker 🤦
Apologies!

**Comment by elParaguayo** [comment]
Great detective work!

I suspect those icons are in different formats. Might be worth seeing if you can check that.

**Comment by elParaguayo** [comment]
> And yes, it also happens in the stock widget, so I even posted the bug on the wrong tracker 🤦 Apologies!

No problem at all - it would be me fixing it one way or the other!

**Comment by arjan-s** [comment]
Yup, looks like it's SVG that isn't working.
The icons that are working for me are only available as PNG in the repo (example: https://gitlab.gnome.org/GNOME/network-manager-applet/-/tree/main/icons/22/nm-stage02-connecting04.png) while some others are also available as SVG (example: https://gitlab.gnome.org/GNOME/network-manager-applet/-/tree/main/icons/scalable/nm-device-wired.svg).

**Comment by arjan-s** [comment]
I tested that, but it doesn't fix the problem.
Tbh I think it is a Qtile issue. I don't know the code that well, but it looks like the `StatusNotifier` widget doesn't handle svg icons any differently from png icons, and passes them blindly on to cairocffi, which passes them on to gdk-pixbuf, which doesn't support svg.
I think there should be an icon format check in `libqtile/widget/statusnotifier.py` that skips svg icons (or converts them to png).

**Comment by elParaguayo** [comment]
`gdk-pixbuf` does support svg on my system but I don't know a lot about it.

Try:
```python
import gi.repository.GdkPixbuf as pixbuf
for f in pixbuf.Pixbuf.get_formats():
    print f.get_name()
```

**Comment by elParaguayo** [comment]
Don't know if this helps: https://github.com/dino/dino/issues/1024#issuecomment-846354514

**Comment by arjan-s** [comment]
Wow, that was it! Thank you!!
I was thrown off by https://gitlab.gnome.org/GNOME/gdk-pixbuf which doesn't list SVG as a supported file format, and also the source code of gdk-pixbuf not having any reference to SVG. Apparently the format support in gdk-pixbuf works the other way around with the format library announcing its support to gdk-pixbuf. It turns out that I just didn't understand how gdk-pixbuf works...

For possible future searchers arriving here: the way to fix this on NixOS is to add the following to the configuration:
```nix
services.xserver.gdk-pixbuf.modulePackages = [ pkgs.librsvg ];
```
