### ISSUE TITLE
Annoying error in the logs

### ISSUE THREAD

**Issue by ervinpopescu** [elParaguayo/qtile-extras#247]
qtile version: `0.22.2.dev185+g4ecf1bde`

Error:
```
2023-05-20 18:35:53,867 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/githubnotifications.py", line 147, in _read_data
    self.draw()
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/githubnotifications.py", line 156, in draw
    self.drawer.clear(self.background or self.bar.background)
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/decorations.py", line 822, in new_clear
    decoration.draw()
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/decorations.py", line 418, in draw
    self.drawer.ctx.reset_clip()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'reset_clip'
```

**Comment by elParaguayo** [comment]
Can you share your config for the githubnotifications widget?

**Comment by ervinpopescu** [comment]
Here it is:
```py
widget.GithubNotifications(
        active_colour=colors["red"],
        icon_size=bar_height - 15,
        inactive_colour=colors["darkblue"],
        mouse_callbacks={
            "Button1": lazy.spawn(
                ["xdg-open", "https://github.com/notifications"],
            ),
            "Button3": lazy.widget["githubnotifications"].eval("self.update()"),
        },
        padding=10,
        token_file=qtile_path + "/github_token",
    )
```

**Comment by elParaguayo** [comment]
Does it have a decoration?

**Comment by ervinpopescu** [comment]
Whoops, forgot that part. 

```py
decorations=[
            RectDecoration(
                colour=decor_bg,
                radius=20,
                filled=True,
                padding_y=0,
                padding_x=0,
            ),
        ],
```

**Comment by elParaguayo** [comment]
Can't recreate this one. How regularly does it happen for you?

**Comment by ervinpopescu** [comment]
Yeah, I feared that would be the case. I'm not sure actually, right now my logs are clear of it.
