### ISSUE TITLE
RectDecoration has no attribute: is_first

### ISSUE THREAD

**Issue by Galax028** [elParaguayo/qtile-extras#248]
Python version: `3.11.3`
Qtile version: `0.22.1-4`
Qtile Extras version: `0.22.2.dev104+gda6ce83`
Distro: `Archlinux x86-64 6.3.4-arch1-1`

My decorations were gone and replaced with empty space so I decided to look at the log files and saw this error repeating:
```
2023-05-28 14:54:17,391 ERROR libqtile loop.py:_handle_exception():L63 RectDecoration has no attribute: is_first
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/libqtile/core/manager.py", line 862, in f
    func(*args)
  File "/usr/lib/python3.11/site-packages/libqtile/bar.py", line 616, in _actual_draw
    i.draw()
  File "/usr/lib/python3.11/site-packages/libqtile/widget/base.py", line 580, in draw
    self.drawer.clear(self.background or self.bar.background)
  File "/usr/lib/python3.11/site-packages/qtile_extras-0.22.2.dev104+gda6ce83-py3.11.egg/qtile_extras/widget/decorations.py", line 822, in new_clear
    decoration.draw()
  File "/usr/lib/python3.11/site-packages/qtile_extras-0.22.2.dev104+gda6ce83-py3.11.egg/qtile_extras/widget/decorations.py", line 420, in draw
    self._draw_path()
  File "/usr/lib/python3.11/site-packages/qtile_extras-0.22.2.dev104+gda6ce83-py3.11.egg/qtile_extras/widget/decorations.py", line 330, in _draw_path
    if self.is_first:
       ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: RectDecoration has no attribute: is_first
```

What should've been shown:
![image](https://github.com/elParaguayo/qtile-extras/assets/72642849/c1475836-a97d-4dc2-92f0-ebd5441a7a14)

What happened:
![image](https://github.com/elParaguayo/qtile-extras/assets/72642849/0fa6fe9f-0de2-4d00-b17f-fad4a6866aee)

If needed, my [configs](https://github.com/Galax028/dotfiles) are here.

**Comment by elParaguayo** [comment]
Was this following an upgrade? That grouping code hasn't been modified for months.

Is there anything else that you've changed?

It's very weird because the decoration *does* have that attribute and I'm struggling to see how that error could arise!

**Comment by Galax028** [comment]
Yes, I just did a system upgrade prior to this. Is it perhaps because Python got updated from 3.10 -> 3.11?

**Comment by elParaguayo** [comment]
Did you reinstall qtile-extras after the upgrade?

The tests run ok on python 3.11 so it should be ok.

**Comment by Galax028** [comment]
First thing I tried after the upgrade was reinstalling, and it is still not working.

**Comment by elParaguayo** [comment]
Ok. Let me try with your config later.

**Comment by elParaguayo** [comment]
Wow - this is really weird.

I get the same error using your config. However, if I call `dir` on the decoration just before that error then I can see that that attribute **is** listed. So I've no idea why I'm getting that error. Will need to dog some more.

Did this config work in python 3.10?

**Comment by Galax028** [comment]
Yep, it worked without an issue on Python 3.10 before I upgraded my system.

**Comment by elParaguayo** [comment]
I think I've found the bug but it's not python 3.10/11 related (or not as far as I can tell). Can you take a look at #249 and see if it fixes it for you?

**Comment by Galax028** [comment]
Hey, sorry for the late reply. Just tried it out and it was working again, thanks a lot @elParaguayo!

**Comment by elParaguayo** [comment]
Great. I'll merge that PR then.
