### ISSUE TITLE
PulseVolumeExtra error

### ISSUE THREAD

**Issue by researcher2312** [elParaguayo/qtile-extras#302]
When I create PulseVolumeExtra widget it displays nothing when in bar mode and in popup mode. PulseVolume widget works fine. Log:

```
ERROR libqtile core.py:_xpoll():L370 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 345, in _xpoll
    self.handle_event(event)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 312, in handle_event
    ret = target(event)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/window.py", line 1488, in handle_ButtonPress
    self.process_button_click(e.event_x, e.event_y, e.detail)
  File "/usr/lib/python3.11/site-packages/libqtile/bar.py", line 541, in process_button_click
    widget.button_press(
  File "/usr/lib/python3.11/site-packages/libqtile/widget/volume.py", line 144, in button_press
    self.draw()
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/base.py", line 279, in draw
    bar_colour = next(x[1] for x in self.colours if self.volume <= x[0])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

**Comment by elParaguayo** [comment]
Is your volume greater than 100%?

**Comment by researcher2312** [comment]
Yes, it appears that the PulseVolume allows for volumes greater than 100%

**Comment by elParaguayo** [comment]
Ok. I'll add some code to catch that scenario.

**Comment by researcher2312** [comment]
And do you know anything about the popup? When i change the mode to popup, I get a different error:

```
ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/pulse_volume.py", line 81, in _check_pulse_connection
    await self.pulse.connect()
  File "/home/researcher/.local/lib/python3.11/site-packages/pulsectl_asyncio/pulsectl_async.py", line 122, in connect
    self._ctx_init()
  File "/home/researcher/.local/lib/python3.11/site-packages/pulsectl_asyncio/pulsectl_async.py", line 110, in _ctx_init
    self._ctx = c.pa.context_new(self._loop.api_pointer, self.name)
                                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'api_pointer'
```
I have pulsectl_asyncio installed

**Comment by elParaguayo** [comment]
I'll need to look into that one too.

**Comment by elParaguayo** [comment]
I can't recreate that one. Popup works ok for me. Can you give me some steps to try?

**Comment by elParaguayo** [comment]
Still can't recreate this.
