### ISSUE TITLE
After an update to 0.25.0 lazy calls stopped working in custom popup windows

### ISSUE THREAD

**Issue by MagnuSiwy** [elParaguayo/qtile-extras#336]
For some reason after the update I can't use lazy calls in the custom popups. Neither lazy.function(), lazy.spawn() nor lazy.shutdown() are working now.

[Here](https://github.com/MagnuSiwy/dotfilesQtile/blob/main/config/qtile/functions.py) are the configs of both of the functions. Both popups work perfectly, just the lazy calls don't

Edit: The power menu function is basically the same as the example in the docs

**Comment by elParaguayo** [comment]
Can't recreate this. Lazy calls work fine for me.

**Comment by MagnuSiwy** [comment]
I get this error every time I try to use the lazy call in a popup:

```2024-04-24 22:55:20,505 ERROR libqtile core.py:_xpoll():L369 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 344, in _xpoll
    self.handle_event(event)
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/core.py", line 311, in handle_event
    ret = target(event)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/backend/x11/window.py", line 1530, in handle_ButtonPress
    self.process_button_click(e.event_x, e.event_y, e.detail)
  File "/usr/lib/python3.11/site-packages/qtile_extras/popup/toolkit.py", line 407, in process_button_click
    control.button_press(x - control.offsetx, y - control.offsety, button)
  File "/usr/lib/python3.11/site-packages/qtile_extras/popup/toolkit.py", line 939, in button_press
    status, val = self.qtile.server.call(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/command/interface.py", line 411, in call
    selectors, name, args, kwargs, lifted = data
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 4)```

It's probably an issue on my end then. Also with just qitle and not qtile-extras, sorry. Do you know how can I fix it? Or should I create an issue on qtile's github?

**Comment by elParaguayo** [comment]
Ah. That's something that was recently added to qtile. That will need fixing in qtile-extras. Won't take long to do.

**Comment by elParaguayo** [comment]
#337 should fix this for you.
