### ISSUE TITLE
Import Error: StatusNotifier

### ISSUE THREAD

**Issue by cr1ogen** [elParaguayo/qtile-extras#350]
The widget had this same error as in Qtile https://github.com/qtile/qtile/pull/4856, but with the fix of this bug, it now gives an error in this one.

```2024-06-03 15:43:42,310 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/qtile_extras/widget/statusnotifier.py", line 44, in attach_menu
    self.is_context_menu = await self.item.get_item_is_menu()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cr1ogen/.local/lib/python3.11/site-packages/dbus_next/aio/proxy_object.py", line 118, in property_getter
    BaseProxyInterface._check_method_return(msg, 'v')
  File "/home/cr1ogen/.local/lib/python3.11/site-packages/dbus_next/proxy_object.py", line 62, in _check_method_return
    raise DBusError._from_message(msg)
dbus_next.errors.DBusError: The name :1.45 was not provided by any .service files
2024-06-03 15:45:07,208 WARNING libqtile base.py:__getattr__():L271 Deprecation Warning: commands exposed via IPC no longer use the 'cmd_' prefix. Please replace 'cmd_spawn' with 'spawn' in your code.
2024-06-03 15:45:09,240 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2024-06-03 15:45:16,994 WARNING libqtile __init__.py:import_class():L108 Unmet dependencies for 'qtile_extras.widget.statusnotifier.StatusNotifier': cannot import name 'StatusNotifierItem' from 'libqtile.widget.statusnotifier' (/usr/local/lib/python3.11/dist-packages/libqtile/widget/statusnotifier.py)```

**Comment by elParaguayo** [comment]
Ah yeah. I moved some code around. Will fix shortly.

**Comment by elParaguayo** [comment]
#351 should fix this.

**Comment by cr1ogen** [comment]
> #351 should fix this.

Works for me. Thank you

**Comment by elParaguayo** [comment]
It will close automatically when the PR is merged.

**Comment by cr1ogen** [comment]
Ok, thanks
