### ISSUE TITLE
StatusNotifier Widget Exception on Shutdown

### ISSUE THREAD

**Issue by phragment** [elParaguayo/qtile-extras#370]
I noticed an exception occuring during shutdown of Qtile using the StatusNotifier widget from qtile-extras:

> libqtile: exception during finalize
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/libqtile/core/manager.py", line 315, in _finalize_configurables
    widget.finalize()
  File "/usr/lib/python3.12/site-packages/libqtile/widget/statusnotifier.py", line 159, in finalize
    host.unregister_callbacks(
  File "/usr/lib/python3.12/site-packages/libqtile/widget/helpers/status_notifier/statusnotifier.py", line 670, in unregister_callbacks
    self._on_item_added.remove(on_item_added)
ValueError: list.remove(x): x not in list

This does not happen when using the widget from qtile.
I can reproduce this behavior on both X11 and Wayland backends.

Versions: qtile 0.27.0 qtile-extras 18509c9

**Comment by elParaguayo** [comment]
Can you try the fix in qtile/qtile#4955

**Comment by phragment** [comment]
Yes, it works for me. Thank you!
