### ISSUE TITLE
`StatusNotifier` menu not opening (Wayland)

### ISSUE THREAD

**Issue by ervinpopescu** [elParaguayo/qtile-extras#376]
Traced it back to this:

```python
2024-09-10 12:46:47,263 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.12/site-packages/qtile_extras/resources/dbusmenu/__init__.py", line 273, in parse_menu
    callback(menu)
  File "/usr/lib/python3.12/site-packages/qtile_extras/widget/mixins/__init__.py", line 281, in display_menu
    self.menu = self._build_menu(self.qtile, menu_items, **self.menu_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qtile_extras/popup/menu.py", line 226, in from_dbus_menu
    return cls.generate(qtile, menuitems, **config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qtile_extras/popup/menu.py", line 250, in generate
    return cls(qtile, controls=menuitems, **menu_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qtile_extras/popup/menu.py", line 180, in __init__
    PopupGridLayout.__init__(self, qtile, controls=controls, **config)
  File "/usr/lib/python3.12/site-packages/qtile_extras/popup/toolkit.py", line 682, in __init__
    _PopupLayout.__init__(self, qtile, **config)
  File "/usr/lib/python3.12/site-packages/qtile_extras/popup/toolkit.py", line 99, in __init__
    self._width = self.width - 2 * self.margin
                  ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

App in scope was `blueman-applet`, fyi.

Any idea what's happening here?

**Comment by ervinpopescu** [comment]
Just finished configuring Wayland like my previous X11 config and I'm not seeing this anymore, closing.
