### ISSUE TITLE
`RoundedCorners` border decoration not working

### ISSUE THREAD

**Issue by ervinpopescu** [elParaguayo/qtile-extras#378]
```
2024-09-23 20:51:42,521 ERROR libqtile group.py:layout_all():L162 Exception in layout monadwide
Traceback (most recent call last):
  File "/home/ervin/.local/lib/python3.12/site-packages/libqtile/group.py", line 160, in layout_all
    self.layout.layout(normal, screen_rect)
  File "/home/ervin/.local/lib/python3.12/site-packages/libqtile/layout/base.py", line 61, in layout
    self.configure(i, screen_rect)
  File "/home/ervin/.local/lib/python3.12/site-packages/libqtile/layout/xmonad.py", line 421, in configure
    client.place(
  File "/home/ervin/.local/lib/python3.12/site-packages/libqtile/backend/wayland/xdgwindow.py", line 315, in place
    self.paint_borders(bordercolor, borderwidth)
  File "/home/ervin/.local/lib/python3.12/site-packages/libqtile/backend/wayland/window.py", line 357, in paint_borders
    color_ = _rgb(color)
             ^^^^^^^^^^^
  File "/home/ervin/.local/lib/python3.12/site-packages/libqtile/backend/wayland/window.py", line 73, in _rgb
    return ffi.new("float[4]", utils.rgb(color))
                               ^^^^^^^^^^^^^^^^
  File "/home/ervin/.local/lib/python3.12/site-packages/libqtile/utils.py", line 140, in rgb
    raise ValueError("Invalid RGB specifier.")
ValueError: Invalid RGB specifier.
```

Config:
```py
    border_focus=RoundedCorners(),
    border_normal=RoundedCorners(),
```

**Comment by elParaguayo** [comment]
How did you import `RoundedCorners`?

**Comment by ervinpopescu** [comment]
```py
from qtile_extras.layout.decorations.borders import RoundedCorners
```

Suggested by `ruff` since it's a private import if I follow https://qtile-extras.readthedocs.io/en/latest/manual/how_to/borders.html#border-decorations.

Same thing with:
 ```py
from qtile_extras.layout.decorations import RoundedCorners
```

**Comment by ervinpopescu** [comment]
WAI. :) Sorry for opening this so fast, will first reach out on Discord in the future.

**Comment by elParaguayo** [comment]
All good and nice to see people trying out these features!
