### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_layout'

### ISSUE THREAD

**Issue by DeeeeLAN** [elParaguayo/qtile-extras#384]
I am not sure what is causing the error, but this is all over my logfile. 

```
2024-10-21 12:51:23,277 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.12/site-packages/qtile_extras/resources/dbusmenu/__init__.py", line 273, in parse_menu
    callback(menu)
  File "/home/dillan/.config/qtile/widgets/globalmenu.py", line 152, in parse_root_menu
    layout = self.drawer.textlayout(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 330, in textlayout
    textlayout = TextLayout(
                 ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/libqtile/backend/base/drawer.py", line 391, in __init__
    layout = drawer.ctx.create_layout()
             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_layout'
```

**Comment by elParaguayo** [comment]
Which widget?

Also, do you reload your config regularly?
