### ISSUE TITLE
How to use the extra StatusNotifier version?

### ISSUE THREAD

**Issue by mcnuggetsx20** [elParaguayo/qtile-extras#87]
I'm on Arch and I have the qtile-extras-git package installed. I tried:
```
from qtile_extras import widget as ewidget
                ewidget.StatusNotifier(
                    highlight_colour=dviolet,
                    menu_foreground = gray,
                    #menu_background = dgray,
                    menu_font = widget_defaults['font'],
                    menu_fontsize = widget_defaults['fontsize'],
                    menu_row_height = 11,
                    icon_size=18,
                    padding=5,
                ),
```
The menu popup doesn't draw when I click on the icon.

**Comment by elParaguayo** [comment]
It should appear with the right-click.

**Comment by mcnuggetsx20** [comment]
I know, but it doesn't.

**Comment by elParaguayo** [comment]
Then I need more information...

What app is this?
Are there any errors in the log file?

**Comment by mcnuggetsx20** [comment]
```py
2022-08-02 08:36:42,181 ERROR libqtile loop.py:_handle_exception():L63 'left'
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/qtile_extras/resources/dbusmenu/__init__.py", line 247, in parse_menu
    callback(menu)
  File "/usr/lib/python3.10/site-packages/qtile_extras/widget/statusnotifier.py", line 169, in display_menu
    self.menu = PopupMenu.from_dbus_menu(self.qtile, menu_items, **self.menu_config)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/menu.py", line 188, in from_dbus_menu
    return cls.generate(qtile, menuitems, **config)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/menu.py", line 212, in generate
    return cls(qtile, controls=menuitems, **menu_config)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/menu.py", line 146, in __init__
    PopupGridLayout.__init__(self, qtile, controls=controls, **config)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 414, in __init__
    _PopupLayout.__init__(self, qtile, **config)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 107, in __init__
    self.keys = {k: [keysyms[key.lower()] for key in v] for k, v in self.keymap.items()}
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 107, in <dictcomp>
    self.keys = {k: [keysyms[key.lower()] for key in v] for k, v in self.keymap.items()}
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 107, in <listcomp>
    self.keys = {k: [keysyms[key.lower()] for key in v] for k, v in self.keymap.items()}
KeyError: 'left'
```

Found this error in the log file. And also, the menu fails to appear for every app I tried so far but since there's that error, I think it's no surprise.

**Comment by elParaguayo** [comment]
You need to be running latest git version of qtile.

**Comment by elParaguayo** [comment]
I'll do tagged releases from next release of qtile but, for now, you need to run latest version.

**Comment by mcnuggetsx20** [comment]
Yeah, it works now. Thanks a lot!
